# Generated by Django 4.2.5 on 2023-09-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
    ]
