# Generated by Django 4.2.5 on 2023-09-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog_web', '0002_rename_article_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
